//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguritas.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class scCobertura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scCobertura()
        {
            this.soPlanCobertura = new HashSet<soPlanCobertura>();
        }
    
        public int scCoId { get; set; }
        public string scCoNombre { get; set; }
        public string scCobSuma { get; set; }
        public System.DateTime scCoFechaMod { get; set; }
        public bool scCoEstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soPlanCobertura> soPlanCobertura { get; set; }
    }
}
