//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguritas.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class scPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scPlan()
        {
            this.soClientePlan = new HashSet<soClientePlan>();
            this.soPlanCobertura = new HashSet<soPlanCobertura>();
        }
    
        public int scPId { get; set; }
        public string scPNombre { get; set; }
        public System.DateTime scPFechaMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soClientePlan> soClientePlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soPlanCobertura> soPlanCobertura { get; set; }
    }
}
