//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguritas.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class scUsuario
    {
        public int scUId { get; set; }
        public string scUNombre { get; set; }
        public string scUUsuario { get; set; }
        public string scUPassword { get; set; }
    }
}
