//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguritas.Entidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguritasEntities : DbContext
    {
        public SeguritasEntities()
            : base("name=SeguritasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<scCliente> scCliente { get; set; }
        public virtual DbSet<scCobertura> scCobertura { get; set; }
        public virtual DbSet<scPlan> scPlan { get; set; }
        public virtual DbSet<scUsuario> scUsuario { get; set; }
        public virtual DbSet<soClientePlan> soClientePlan { get; set; }
        public virtual DbSet<soPlanCobertura> soPlanCobertura { get; set; }
    }
}
