//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguritas.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class soClientePlan
    {
        public int soCPId { get; set; }
        public int soCPCId { get; set; }
        public int soCPPId { get; set; }
        public bool soCPEstatus { get; set; }
        public System.DateTime soCPFechaMod { get; set; }
    
        public virtual scCliente scCliente { get; set; }
        public virtual scPlan scPlan { get; set; }
    }
}
